local vars = require("conf/variables")

hl.on("hyprland.start", function()
    hl.exec_cmd("qs -c main")
    hl.exec_cmd("vicinae server")
    
    -- hl.exec_cmd("hyprctl dispatch exec '[workspace 1 silent] " .. vars.browser .. "'")
    -- hl.exec_cmd("hyprctl dispatch exec '[workspace 13 silent] " .. vars.telegram .. "'")
hl.exec_cmd("hyprctl dispatch workspace 13")
    -- hl.exec_cmd("hyprctl dispatch exec '[workspace 1 silent] " .. vars.browser .. "'")
    -- hl.exec_cmd("hyprctl dispatch exec '[workspace 13 silent] " .. vars.telegram .. "'")
    hl.exec_cmd("systemctl --user start wallpaper.service")
    -- hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    -- hl.exec_cmd("kbuildsycoca6")
    -- hl.exec_cmd("hyprsunset")
end)